### ISSUE TITLE
Change Link Button to Anchor Tag and also fix links

### ISSUE THREAD

**Issue by sahsisunny** [Real-Dev-Squad/website-dashboard#285] opened 2023-01-17 00:13 UTC
## Issue: Change Link Button to Anchor Tag and Fix links

**Description**:
In the website, some buttons not redirecting to the correct page. And some buttons are not working at all. The current link button on the website is using the `<button>` element, which is not considered best practice for creating links. It is recommended to use the `<a>` (anchor) element for creating links.

**What to do**:
- Change the link button to an anchor tag.
- Add the appropriate `href` attribute to the anchor tag.
- Fix the links that are not working.
- All the anchor tags should look the same as the current link button.

**Where to find the issue**:
- [x] [Home Page](https://dashboard.realdevsquad.com/) - User Management Button

Note : Make sure to check the all anchor tag buttons on the website look the same as the current link button.

**Comment by c00kie123** [comment] 2023-01-17 06:28
Hi I am interested in this! Assign it to me

**Comment by Dcode2100** [comment] 2023-01-17 07:23
If the issue is open assign this to me

**Comment by c00kie123** [comment] 2023-01-17 08:22
Thanks @sahsisunny I will work on it asap!

**Comment by sahsisunny** [comment] 2023-01-18 00:48
any update @c00kie123 ?

**Comment by c00kie123** [comment] 2023-01-18 01:14
hi @sahsisunny, check #287

**Comment by sahsisunny** [comment] 2023-01-20 00:27
issues if fix in #283 PR. [See this for more info](https://github.com/Real-Dev-Squad/website-dashboard/pull/283/commits/d5b40709b098fa8a6a486c67873c99ef5aee571a)

**Closed** 2023-02-05 00:09 UTC
Labels: good first issue, beginner friendly
